services:
  ps2-opl-smb:
    build: .
    image: ps2-opl-smb
    container_name: ps2-opl-smb
    restart: unless-stopped
    ports:
      - "139:139"
      - "445:445"
    volumes:
      - /Volumes/WANDERER/PS2SMB:/srv/samba
