[global]
workgroup = WORKGROUP
server string = PS2 OPL SMB
server role = standalone server
security = user
map to guest = Bad User
guest account = nobody
server min protocol = NT1
server max protocol = SMB3

[PS2SMB]
path = /srv/samba
browseable = yes
guest ok = yes
read only = no
force user = root
create mask = 0666
directory mask = 0777
